### ISSUE TITLE
fix: 404 for web-components-v2.5.16.min.js in 4.2.0 template

### ISSUE THREAD

**Issue by danielgreen** [microsoft/fluentui-blazor#1131]
# 🐛 Bug Report

Followed the recommendation to reference `web-components-v2.5.16.min.js` in `App.razor` to enable web components for SSR pages, but the browser gets a 404 not found response for the script.

May relate to #623 

Specifically this comment from Vincent:
https://github.com/microsoft/fluentui-blazor/issues/623#issuecomment-1683752876

## 💻 Repro or Code Sample

Install the template using `dotnet new install Microsoft.FluentUI.AspNetCore.Templates`.
Create a new Blazor Web App from the VS 2022 new project dialog.
Select interactive mode Auto per page. Server and Client projects are generated.

In App.razor, add the following below the `blazor.web.js` script tag.
`<script src="_content/Microsoft.FluentUI.AspNetCore.Components/js/web-components-v2.5.16.min.js" type="module" async></script>`

Launch the app. In the DevTools network tab, observe a 404 response for web-components-v2.5.16.min.js.

Seeing the same behavior when creating a standalone Blazor Server web app from a command prompt
e.g. `dotnet new fluentblazor -o BlazorWebApp`.

## 🌍 Your Environment

Windows 11, VS 17.8.3, Chrome, .NET 8, FluentUI 4.2.0

**Comment by vnbaaij** [comment]
Hi, I need to update that recommendation for v4.2. Where exactly did you find that?

For v4.2 the way we bundle the scripts has changed. You should now use:
```
<script type="module" async src="./_content/Microsoft.FluentUI.AspNetCore.Components/Microsoft.FluentUI.AspNetCore.Components.lib.module.js"></script>
```

Please let me know here if that helps solve the issue. Thanks.

**Comment by iwhp** [comment]
I just installed `dotnet new install Microsoft.FluentUI.AspNetCore.Templates` (v4.2.0) and there is still a reference to `web-components-v2.5.16.min.js`.

So probably the code in `https://github.com/microsoft/fluentui-blazor/blob/dev/src/Templates/content/BlazorWeb-CSharp/BlazorWeb-CSharp/Components/App.razor` should be fix.

**Comment by danielgreen** [comment]
> Hi, I need to update that recommendation for v4.2. Where exactly did you find that?
> 
> For v4.2 the way we bundle the scripts has changed. You should now use:
> 
> ```
> <script type="module" async src="./_content/Microsoft.FluentUI.AspNetCore.Components/Microsoft.FluentUI.AspNetCore.Components.lib.module.js"></script>
> ```
> 
> Please let me know here if that helps solve the issue. Thanks.

It's in the main README for this repo:
https://github.com/microsoft/fluentui-blazor#script

Also in the Code Setup page:
https://www.fluentui-blazor.net/CodeSetup

If a reference to `Microsoft.FluentUI.AspNetCore.Components.lib.module.js` replaces the old guidance, I don't appear to need it in `App.razor` explicitly, because when I omit it from there, I still see it being loaded in the DevTools network tab anyway (initiated by `blazor.web.js`).

**Comment by vnbaaij** [comment]
I've updated the docs.

> If a reference to `Microsoft.FluentUI.AspNetCore.Components.lib.module.js` replaces the old guidance, I don't appear to need it in `App.razor` explicitly, because when I omit it from there, I still see it being loaded in the DevTools network tab anyway (initiated by `blazor.web.js`).

Yes, this is only needed in SSR situations where our script would not be loaded because Blazor is not around to load it for us (as in non-SSR scenarios)

**Comment by danielgreen** [comment]
Even on static pages, the web components script still appears to be loaded by blazor.web.js.

Am I missing something - the page I'm testing has no `@rendermode` (and there's no rendermode set in the parent layout components).

`App.razor` references the Blazor script, which loads on all pages (including SSR):
`<script src="_framework/blazor.web.js"></script>`

Unclear why it subsequently loads the web components js on a static page, when the web components js is omitted from `App.razor`.

**Comment by vnbaaij** [comment]
With the `{modulename}.lib.module.js` construct, Blazor will automatically pick up the script. This allows us to get the web components loaded without any actions from the developer's side. See also https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/startup?view=aspnetcore-8.0#javascript-initializers

**Comment by danielgreen** [comment]
The web components script appears to load on an SSR page even when not directly referenced in App.razor, which I didn't expect given the guidance to explicitly add the reference to App.razor. Which makes me think I am doing something wrong.

**Comment by vnbaaij** [comment]
It was that way before v4.2. We now have a new way in of getting our scripts created (with an extra (new) javacsript project file (.esproj)). I have not updated all the guidance at all te right places yet. Sorry for the confusion created. Hope to get it all rectified next week.

**Comment by vnbaaij** [comment]
Fixed in 4.2.1 templates
