### ISSUE TITLE
FluentComboBox and FluentSelect don't work with mouse selection in Microsoft.Maui.Controls v8.0.14

### ISSUE THREAD

**Issue by euantorano** [microsoft/fluentui-blazor#1741]
# 🐛 Bug Report

When upgrading `Microsoft.Maui.Controls` and/or `Microsoft.Maui.Controls.Compatibility`, the `<FluentComboBox>` and `<FluentSelect>` stop accepting mouse inputs to select items. Keyboard actions to select items still work.

`Microsoft.Maui.Controls` > 8.0.7 causes this bug.
`Microsoft.Maui.Controls.Compatibility` > 8.0.7 causes this bug.

Using older versions of these libraries (e.g. using 8.0.7 for both) resolves the problem.

Note that other components may also be broken, but I have observed both `FLuentCombobox` and `FluentSelect` myself.

## 💻 Repro or Code Sample

See repository: https://github.com/euantorano/fluentui-combo-and-select

Branch `main` does not work, but the branch `working-version` does work.

## 🤔 Expected Behavior

Selecting items with the mouse should work for both `FluentComboBox` and `FluentSelect`.

## 😯 Current Behavior

Selecting items with the mouse does not work.

![7tvOT60LIM](https://github.com/microsoft/fluentui-blazor/assets/748913/52432c1b-1392-459c-8e0f-4c98b05d6a2a)

## 💁 Possible Solution

N/A - apart from downgrading dependencies

## 🔦 Context

N/A

## 🌍 Your Environment

* OS & Device: Windows 11 on PC
* .NET and Fluent UI Blazor library Version - 8.0.3 and 4.5.0

**Comment by jamesmontemagno** [comment]
@eilon did we change something in the blazor hybrid web view that folks need to specify the render type? do folks need interactivity enabled somehow?

**Comment by subratb** [comment]
Seems like [this issue](https://github.com/MicrosoftEdge/WebView2Feedback/issues/3003) has resurfaced again. When we had the issue earlier, we solved it by adding a package reference to a particular version of Microsoft.WindowsAppSDK(1.4.231115000). But, now we have the same issue again.

**Comment by mohit-x0** [comment]
I am also facing the same issue, selecting items `<FluentSelect>` with the mouse does not work on Windows, but it works on Android.

**Comment by vnbaaij** [comment]
It seems to be a regression on the MAUI side. We are blocked till it is fixed there.

**Comment by jem-experience** [comment]
Oh thank you, -1 in my backlog, i had the same issue for weeks after a big UI redesign from pure html css to fluentui components, i was thinking at a css thing so i push myself really hard to delay the investigation, i have others issues, with no css involved, to manage!
I solved it by downgrading the Microsoft.Maui.Essentials  to version="8.0.6" and the 2 others previously mentionned and everything is fine now!

**Comment by euantorano** [comment]
Looks like this is still broken in v8.0.21. Is there any timeline for a fix on the MAUI side or a link to an issue on that side of things?

**Comment by vnbaaij** [comment]
You should really ask that in the MAUI repo. We are not on that team and do not have any insights into their planning/roadmap

**Comment by euantorano** [comment]
OK. When you came to the conclusion in https://github.com/microsoft/fluentui-blazor/issues/1741#issuecomment-2032702895, what made you realise it was a regression on their side? When I open an issue over there I want to provide as much detail as I can.

**Comment by vnbaaij** [comment]
Based on the fact that it worked fine with version 8.0.6 or 7 of the Microsoft.Maui.Componets library.

**Comment by euantorano** [comment]
OK, thanks. I'll open an issue with them.

**Comment by Eilon** [comment]
This appears to be a bug in WinUI WebView2 specifically. I opened a MAUI-less repro bug here: https://github.com/MicrosoftEdge/WebView2Feedback/issues/4545

**Comment by vnbaaij** [comment]
Please don't mix issues. Create a new issue  for what you are seeing. This one is very specific for MAUI as can be seen in the linked issue in the WebView repo

**Comment by AlexanderChaker** [comment]
Using Fluent UI v4.10.2 with MAUI Net9.0 on Windows.
This issue seems to be fixed now. I can open a dropdown and select an item.

**Comment by vnbaaij** [comment]
That is great news! Thanks for the update. Closing this issue then.
