### ISSUE TITLE
FluentNavLink - When Href is specified the Disabled link color is not applied

### ISSUE THREAD

**Issue by coderdnewbie** [microsoft/fluentui-blazor#1992]
When using this, the disabled color is applied correctly:

`<FluentNavLink Icon="@(new Icons.Regular.Size24.CalendarAgenda())" Disabled="true" Tooltip="Item 4 tooltip1">Item 4 Disabled</FluentNavLink>`

However when using this, the disabled color is not applied:

`<FluentNavLink Icon="@(new Icons.Regular.Size24.CalendarAgenda())" Disabled="true" Href="https://microsoft.com" Tooltip="Item 4 tooltip1">Item 4 Disabled</FluentNavLink>`

The only difference is the second one has Href="https://microsoft.com"

Please can the disabled color also be applied for the second scenario

**Comment by vnbaaij** [comment]
Fixed in next release:

![image](https://github.com/microsoft/fluentui-blazor/assets/1761079/fa18e36f-525c-4d9d-9f98-7fa072861c50)

**Comment by coderdnewbie** [comment]
I have tested in release 4.7.2. It is still happening will wait for 4.7.3. If it is in 4.7.2, please let me know.

**Comment by vnbaaij** [comment]
Make sure to do a hard refresh as this is primarily a CSS change.
Just checked it on the demo site and it looks on, I believe.

**Comment by coderdnewbie** [comment]
Correction. It did work, I am sorry for the error, but for the last hour it did not work, then I rebooted and built it again and it worked as expected. Sorry for the mistake, I am not sure what is going on with my Visual Studio.
