### ISSUE TITLE
fix: [auto Change GridTemplateColumns property after upgrade to v4.11.4 in FluentDatagrid

### ISSUE THREAD

**Issue by abednejad** [microsoft/fluentui-blazor#3393]
# 🐛 Bug Report

I used FluentDatagrid v4.11.1 
For Set the width of each column to be fixed value, I Used GridTemplateColumns property after upgrading to v 4.11.4  the value of this propery change to "auto" for each column

## 💻 Repro or Code Sample

     <FluentDataGrid @ref="ShellFac2Grid"
                     Items="ShellFactorsItems"
                     Pagination="@paginationState"
                     ItemSize="40"
                     ResizableColumns="true"
                     ResizeType="DataGridResizeType.Discrete"
                     Virtualize="true"
                     ShowHover="true"                                        
                     GridTemplateColumns="50px 60px 150px 250px 150px 150px 150px 60px"
                      Style="min-width: max-content;"
                     >

When complie and use Inspector Tool in browser and find the css class reletive to this component ,I found it changed to 

element.style {
    grid-template-columns: 50px auto auto auto auto auto auto auto;
}

## 🤔 Expected Behavior

it expected to be 

element.style {
    grid-template-columns: 50px 60px 150px 250px 150px 150px 150px 60px;
}

right as set in source code

## 😯 Current Behavior

but it changed to 

element.style {
    grid-template-columns: 50px auto auto auto auto auto auto auto;
}

## 💁 Possible Solution

for now I tried to set width value for each column separately like this

                                <Microsoft.FluentUI.AspNetCore.Components.PropertyColumn 
                                                            Property="@(p=> p.Id)" Sortable="true" Title="InvoiceID" Width="150px" />

## 🌍 Your Environment

* OS & Device: [Windows on PC] and Android on Phone
* Browser  Microsoft Edge, Google Chrome,  Mozilla FireFox
* .NET and Fluent UI Blazor library Version9.0.2 and 4.11.4

**Comment by PascalVorwerk** [comment]
Hi! I see a view things potentially wrong with ur datagrid:

```
**GridTemplateColumns="50px 60px 150px 250px 150px 150px 150px 60px"**
```

This should not be inbetween **'s.

You are using both pagination and virtualization at the same time.

When i try your widths on the demo website locally it works fine, it sets the width of columns fine!

**Comment by vnbaaij** [comment]
There was indeed an issue with the GridTemplateColumn in v4.11.4.This has been fixed with the - just released - v4.11.5

**Comment by vnbaaij** [comment]
@abednejad if you re-open this, make sure there is **ready to run reproduction code**. Compare with, for example, https://www.fluentui-blazor.net/datagrid-typical where you can see it is using the set `GridTemplateColumns` values:

![Image](https://github.com/user-attachments/assets/ec22fb5c-f087-4766-aed4-ada0067568d1)

**Comment by abednejad** [comment]
> [@abednejad](https://github.com/abednejad) if you re-open this, make sure there is **ready to run reproduction code**. Compare with, for example, https://www.fluentui-blazor.net/datagrid-typical where you can see it is using the set `GridTemplateColumns` values:
> 
> ![Image](https://github.com/user-attachments/assets/ec22fb5c-f087-4766-aed4-ada0067568d1)

Hi
I don't have permission to reopen this issue

and this problem still exists

**Comment by vnbaaij** [comment]
@abednejad i have reopened the issue. Make sure you add the ready to run reproduction code.

**Comment by abednejad** [comment]
> [@abednejad](https://github.com/abednejad) i have reopened the issue. Make sure you add the ready to run reproduction code.

Hi
Here is a Test Ready for this issue

[App.zip](https://github.com/user-attachments/files/18869434/App.zip)

the database Script file is in   "App\Model"  Folder

**Comment by vnbaaij** [comment]
Ok, error found. Will be fixed in next release.
