### ISSUE TITLE
fix: Visual Studio 2022 freezes and then crashes with v3-RC-1

### ISSUE THREAD

**Issue by StevenRasmussen** [microsoft/fluentui-blazor#643]
# 🐛 Bug Report

After updating the NuGet packages from v2.4.2 to v3.0.0-RC-1 on a .Net 8 Preview 7 Blazor project, Visual Studio 2022 v17.8.0 Preview 1.0 freezes and then crashes within a couple of minutes while trying to edit a razor file.

## 💻 Repro or Code Sample

Note: The following should provide a way for you to reproduce the issue, but the issue manifests itself without doing these things either... it just takes a little longer to crash.  I feel like the issue has to do with the `Icons` package somehow.

1) Clone the repo here: [https://github.com/StevenRasmussen/FluentUIBlazorIssue](https://github.com/StevenRasmussen/FluentUIBlazorIssue)
2) Open the solution
3) Open the `Index.razor` file
4) Try "Going to definition" on the `Delete` icon name or the `Icon` parameter of the `FluentIcon` component on line 9.
5) Then move your cursor back and forth between those two and hover over them to get the tooltip to show.  Usually within performing this 4-5 times, VS will freeze and crash.  Here's a video of it:

![2023-08-24_15-27-20](https://github.com/microsoft/fluentui-blazor/assets/11198735/b549cb76-9935-4016-8c01-990ac3af674c)

## 🤔 Expected Behavior

VS does not freeze and crash

## 🌍 Your Environment

Windows 10 - Latest updates installed
VS 2022 v17.8.0 Preview 1.0
.Net 8.0.100-preview.7
Microsoft.Fast.Components.FluentUI v3.0.0-rc-1
Microsoft.Fast.Components.FluentUI.Icons v3.0.0-rc-1

**Comment by AathifMahir** [comment]
Facing same issue with .Net 7 and Fluent Blazor v3 Stable on Visual Studio 17.7.2 Latest Stable

**Comment by vnbaaij** [comment]
I'm trying to get the Visual Studio team involved on this.

**Comment by AathifMahir** [comment]
> I'm trying to get the Visual Studio team involved on this.

I guess the analyzers are the ones causing this issue. Let's hope this is just a minor bug

**Comment by dvoituron** [comment]
After opening the **Event Viewer**, I saw this error `Failed to read environment variable [DOTNET_STARTUP_HOOKS]` 
Same for you?

I found this article
https://github.com/dotnet/runtime/issues/87687#issuecomment-1635628045

**Comment by StevenRasmussen** [comment]
@dvoituron - Unfortunately I don't see that in event viewer.

**Comment by 0xa1b1c1** [comment]
Facing same issue with .Net 6 (SDK: 6.0.413) and Fluent Blazor v3 Stable on Visual Studio 17.6.3.

**Comment by StevenRasmussen** [comment]
Just to provide some more info: I'm not sure if it's related to analyzers or not.  I tried all of the following solutions but the issue still persists: [https://stackoverflow.com/questions/36461174/how-do-i-disable-all-roslyn-code-analyzers](https://stackoverflow.com/questions/36461174/how-do-i-disable-all-roslyn-code-analyzers).  That being said, it appears that the issue is more related to trying to `Go To Definition`.  In my video above, if I don't try going to the definition then VS appears to be stable... although this is also after I followed all of the tips to disable analyzers... but if I do `Go To Definition` then VS will freeze within 30 seconds (usually quicker).

**Comment by StevenRasmussen** [comment]
It sounds like @vnbaaij is trying to get the VS team involved.  I have not opened an issue since I'm only having this problem with this package... and TBH, I've reported many VS issues and they just seem to go into a black-hole after providing logs and screenshots and wasting a lot of my time... so I've pretty much given up on reporting VS problems to the VS team unfortunately.

**Comment by AathifMahir** [comment]
> It sounds like @vnbaaij is trying to get the VS team involved.  I have not opened an issue since I'm only having this problem with this package... and TBH, I've reported many VS issues and they just seem to go into a black-hole after providing logs and screenshots and wasting a lot of my time... so I've pretty much given up on reporting VS problems to the VS team unfortunately.

I can get behind on this, it's kind of hard to get attention from the VS Team. But this issue seems to be spreading to more users rapidly.

I guess we might need to take care of this as soon as possible. In my case I'm delaying the launch of an app that I was working on for a couple of months due to this issue since we need lots of controls that currently present on Fluent Blazor v3, we can't downgrade to v2 as well

**Comment by vnbaaij** [comment]
I received some pointers/steps to investigate from my internal contact. Will take a look tonight to see if we can find the culprit...

**Comment by AathifMahir** [comment]
Just updated to Visual Studio 17.7.3 and So far it's working fine, no freezes yet

**Comment by vnbaaij** [comment]
Ok, the problem is definitely originates from the `Icons`. What is happening is that by clicking the 'Go to definition' on the `Icon` class the decompiler is being invoked. `Icon` is a **HUGE** constellation of partial classes, which leads the program to going into a recursive algorithm which it **does not** recover from. 

I can reproduce the issue, but when not invoking 'Go to definition', I do experience any chrashes when working with the icons. I am however using a later preview of VS. As @AathifMahir  mentioned, 17.7.3 should work as well.

As said, `Icon` is a **HUGE** partial classes thing, so it does not really surprise me that VS borks on it. We will think about restructuring or designing it differently but that will not be something for the immediate future, I'm afraid. Only thing I can say is, for now, do not use 'Go to definition' on an `Icon` reference...

**Comment by vnbaaij** [comment]
As said, `Icon` is a **HUGE** partial classes thing, so it does not really surprise me that VS borks on it. We will think about restructuring or designing it differently but that will not be something for the immediate future, I'm afraid. 

Only thing I can say is, for now, do not use 'Go to definition' on an `Icon` reference. Closing the issue as there is no immediate action we can take on this.

**Comment by StevenRasmussen** [comment]
@vnbaaij - I can confirm that this DOES NOT only happen when you `F12` or "Go To Definition".  I spent the day yesterday upgrading from v2 in one of my projects and never used the "Go To Definition" but VS consistently crashed about every minute.  This is due to the fact that the largest breaking change is with regards to how `Icons` are handled now.  Everywhere you use `FluentIcon` you have to change the old property `Name` to `Icon`.  This is where I believe VS struggles and will be a HUGE pain point for anyone when they go to upgrade.  I had to kill VS in Task Manager (because I was impatient and did not want to wait for it to crash) every time I upgraded a component that had any `FluentIcon`s that needed changing. It was a race to try and get as many of them updated in a razor page until VS would crash (usually within 20 seconds).

If you're not going to do anything any time soon with regards to this design, then I would highly suggest you put a large banner on the 'Upgrade' page saying that Visual Studio WILL crash multiple times if you have any occurrences of `FluentIcon` that need to be upgraded.

The good news is that now that my project is upgraded it has finally become "stable" and I haven't experienced a crash since.

On a side note... I don't feel like this ticket should be closed since the issue is clearly not fixed.

**Comment by vnbaaij** [comment]
Ok, I re-openend the issue.

It wasn't clear to me that this was also happening with migrating from V2 to V3. I can imagine that inserting/changing the `Icon` parameter will call IntelliSense and VS gets in trouble there.

For our own migration (of the demo site), we used a 'search and replace' tactic that did most of the conversions in one go. Can we put a note about that in the upgrade guide @dvoituron?

**Comment by dvoituron** [comment]
Yes, I will do that tomorrow :-)

In summary, I used the [regular expressions in Visual Studio](https://learn.microsoft.com/en-us/visualstudio/ide/using-regular-expressions-in-visual-studio).
- To search: `<FluentIcon Name="?@?FluentIcons\.(?<name>[^"]+)"? Size="?@?IconSize\.(?<size>[^"]+)"? Variant="?@?IconVariant\.(?<variant>[^"]+)"? Color="?@?Color\.(?<color>[^"]+)"? Slot="?(?<slot>[^"]+)"? />` 
- To replace by: `<FluentIcon Icon="Icons.${variant}.${size}.${name}" Color="@Color.${color}" Slot="${slot}" />`

![image](https://github.com/microsoft/fluentui-blazor/assets/8350694/49e1bdc3-5c8e-46a7-97c6-3c76688abd2d)

The preceding expressions are defined to search for attributes in this order: Name, Size, Variant, Color, Slot.
You may need to change or delete some attributes, depending on how you've coded them.

**Comment by dvoituron** [comment]
Done #673

**Comment by AathifMahir** [comment]
Still Freezing Randomly, It's so annoying. I'm sure Visual Studio Team Needs to Get Involed on this and fix the issue in the roots

**Comment by Lindsay-Mathieson** [comment]
Same problem, everytime I do anything with FluentIcon it ends up hanging, with the MS Bug reporter hogging around 50% cpu. If I kill that, DevStudio is gone and I can restart.

**Comment by vnbaaij** [comment]
As said before, I already involved the VS team. In fact we even pinpointed where exactly the problem occurs. See https://github.com/icsharpcode/ILSpy/issues/3075. Don't know when this will be implemented in a VS release. 
We are trying to get a workaround/different solution in place. Also, no ETA on that.

For now, I would advise to try to go to the latest VS version. Or even preview (as you can have multiple versions of VS installed side by side). According to earlier reports shared here less problems seem to arise then

**Comment by AathifMahir** [comment]
> As said before, I already involved the VS team. In fact we even pinpointed where exactly the problem occurs. See https://github.com/icsharpcode/ILSpy/issues/3075. Don't know when this will be implemented in a VS release. 
> We are trying to get a workaround/different solution in place. Also, no ETA on that.
> 
> For now, I would advise to try to go to the latest VS version. Or even preview (as you can have multiple versions of VS installed side by side). According to earlier reports shared here less problems seem to arise then

Do we have an issue opened in VS Community?

**Comment by vnbaaij** [comment]
No, we have the issue I just linked too. This is the code that is called from VS. That is where the problem is.

**Comment by Lindsay-Mathieson** [comment]
> For now, I would advise to try to go to the latest VS version. Or even preview (as you can have multiple versions of VS installed side by side). According to earlier reports shared here less problems seem to arise then

Thanks, I'll give preview a try, appreciate the work in tracking down the source and that its an issue with VS, not Fluent UI.

**Comment by vnbaaij** [comment]
Please try the `Microsoft.Fast.Components.FluentUI.Icons` v3.0.1 package and let us know if this fixes your VS crashing issues. Our testing shows this works, but we would like to get some confirmation.

**Comment by Narvalex** [comment]
It does not crash when F12 or "Go To Definition" on my side. Thanks guys!

**Comment by AathifMahir** [comment]
Finally, I can confirm it no longer freezes or crashes the Visual Studio with v3.0.1

**Comment by vnbaaij** [comment]
Ok, closing this one then.

**Comment by StevenRasmussen** [comment]
I can confirm that it is now working in the latest VS 2022 preview as well!  Thanks!

**Comment by Lindsay-Mathieson** [comment]
Working well for me in Preview too, haven't had a chance to try 2022.

Thanks!
