### ISSUE TITLE
fix: fluent-data-grid-row css not being applied to columns outside the viewport in fluent-data-grid

### ISSUE THREAD

**Issue by trubby22** [microsoft/fluentui-blazor#709]
# 🐛 Bug Report

When a fluent-data-grid component has a max-width specified, the fluent-data-grid-row components are of fixed width and there's a scrollbar present to move left-right (overflow-x: auto), the css styling specified for a fluent-data-grid-row component gets only applied to the columns in the viewport (i.e. visible to the user on initial render). When we scroll to the right, the previously hidden columns don't have the css styling applied to them.

## 💻 Repro or Code Sample

A small repository demonstrating the issue can be found [here](https://github.com/trubby22/BlazorFluentDataGrid).

The steps needed to create the above repo manually:
1. Install FluentUI templates as specified [here](https://www.nuget.org/packages/Microsoft.Fast.Templates.FluentUI/)
2. Create a new project using the FluentUI WASM template
3. In FetchData.razor file replace the FluentDataGrid component with the following code. What's modified in my version: FluentDataGrid has GridTemplateColumns attribute modified and the component is surrounded with a div component with a style attribute.

```
<div style="overflow-x: auto; max-width: 200px;">
  <FluentDataGrid Id="manualGrid" Items=@forecasts GridTemplateColumns="120px 120px 120px 120px" TGridItem=WeatherForecast>
    <PropertyColumn Title="Date" Property="@(c => c!.Date)" Sortable="true" Align=Align.Start/>
    <PropertyColumn Title="Temp. (C)" Property="@(c => c!.TemperatureC)" Sortable="true" Align=Align.Center/>
    <PropertyColumn Title="Temp. (F)" Property="@(c => c!.TemperatureF)" Sortable="true" Align=Align.Center/>
    <PropertyColumn Title="Summary" Property="@(c => c!.Summary)" Sortable="true" Align=Align.End/>
  </FluentDataGrid>
</div>
```

4. In app.css append the following styling to the end of the file
`fluent-data-grid-row {
  background: palevioletred;
  border-bottom-color: black;
}`

## 🤔 Expected Behavior

The styling specified for the fluent-data-grid-row should be applied to all columns, even the ones that are not in the viewport on initial render. When we scroll to the right to see additional columns, they should have the css applied to them too.

## 😯 Current Behavior

The columns not in initial viewport don't have css applied to them when we scroll right.

What the template grid looks like without my modifications
![Initial fluent-data-grid as in the template without my changes](https://github.com/microsoft/fluentui-blazor/assets/48940836/68147684-9e84-42d3-91a9-8c3ecd2ef347)

What the grid looks like when I applied my modifications
![left](https://github.com/microsoft/fluentui-blazor/assets/48940836/256b8de9-5389-4c50-96ef-a8485082bfdd)
![middle](https://github.com/microsoft/fluentui-blazor/assets/48940836/d4f76a70-3be0-433b-ace9-644d3d11ba11)
![right](https://github.com/microsoft/fluentui-blazor/assets/48940836/565b6d0a-b92f-4bc5-a5d1-9426cf028a83)

## 🔦 Context

I'm trying to display a table with a large number of columns and want the user to scroll the table rather than the enclosing component.

## 🌍 Your Environment

* OS & Device: Windows 11 on PC
* Browser: Google Chrome
* .NET: net6.0;net7.0
* Microsoft.Fast.Components.FluentUI: 3.0.1

**Comment by vnbaaij** [comment]
Hi,

Got some info from one of the web components experts. This is solved if you put a `Style="min-width: 480px;"` in your  FluentDataGrid

**Comment by trubby22** [comment]
Hi,

Thanks for the response. I tried out your proposed solution. It does not solve my problem, though. In my use case I want min-width to be less than the sum of the column widths (as specified in GridTemplateColumns). In the example I made the table very narrow but it's just to demonstrate the problem. In my actual production scenario, there is a table that contains around 20 different columns and it does not fit on a regular laptop / PC screen. Hence I need to show only a portion of the columns at once and have a scrollbar to navigate left-right.

Thanks,
Piotr

**Comment by vnbaaij** [comment]
Wouldn't what we do in the preview demo site (https://preview.fluentui-blazor.net) for mobile devices not work then? The grid is put in a div with a specific size:
```
@media screen and (max-width: 1280px) {
    .docgrid {
        overflow-x: scroll;
    }
} 
```
Then the grid is given a `min-width: 1200 px;` and you can then scroll the grid 
![DataGridScroll](https://github.com/microsoft/fluentui-blazor/assets/1761079/a8088bce-f454-4e6c-b773-fe591663f2ff)

**Comment by trubby22** [comment]
Thank you! This solved my issue.

It seems like GridTemplateColumns need to be set to fractional values and the style needs to include the min-width attribute.
For context, below is the relevant piece of working code.
```
<div style="overflow-x: auto; max-width: 200px;">
    <FluentDataGrid Id="manualGrid" Items=@forecasts GridTemplateColumns="1fr 1fr 1fr 1fr" TGridItem=WeatherForecast
                    Style="min-width: 1200px">
      <PropertyColumn Title="Date" Property="@(c => c!.Date)" Sortable="true" Align=Align.Start/>
      <PropertyColumn Title="Temp. (C)" Property="@(c => c!.TemperatureC)" Sortable="true" Align=Align.Center/>
      <PropertyColumn Title="Temp. (F)" Property="@(c => c!.TemperatureF)" Sortable="true" Align=Align.Center/>
      <PropertyColumn Title="Summary" Property="@(c => c!.Summary)" Sortable="true" Align=Align.End/>
    </FluentDataGrid>
  </div>
```
