### ISSUE TITLE
fix: Exception when trying to override FluentDialogFooter in a FluentDialog

### ISSUE THREAD

**Issue by robotjatek** [microsoft/fluentui-blazor#917]
# 🐛 Bug Report

An exception occurs when trying to override FluentDialogFooter in a FluentDialog.

`System.InvalidOperationException: This FluentDialog already contains a FluentDialogFooter
   at Microsoft.Fast.Components.FluentUI.FluentDialog.SetDialogFooter(FluentDialogFooter footer) in /_/src/Core/Components/Dialog/FluentDialog.razor.cs:line 252
   at Microsoft.Fast.Components.FluentUI.FluentDialogFooter.OnInitialized() in /_/src/Core/Components/Dialog/FluentDialogFooter.razor.cs:line 44
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()`

Overriding `FluentDialogHeader` and `FluentDialogBody` works correctly

## 💻 Repro or Code Sample

This dialog crashes:

```html
<FluentDialog @ref="_dialog" @bind-Hidden="DialogHidden" Modal="true" @ondialogdismiss="OnDialogDismiss">

    <FluentDialogHeader ShowDismiss="true">
        Header
    </FluentDialogHeader>
    <FluentDialogBody>
        This is the body
    </FluentDialogBody>

    <FluentDialogFooter>
        Crash if present, works when commented out
    </FluentDialogFooter>

</FluentDialog>
```

Working example without `FluentDialogFooter`:

```html
<FluentDialog @ref="_dialog" @bind-Hidden="DialogHidden" Modal="true" @ondialogdismiss="OnDialogDismiss">

    <FluentDialogHeader ShowDismiss="true">
        Header
    </FluentDialogHeader>
    <FluentDialogBody>
        This is the body
    </FluentDialogBody>

</FluentDialog>
```

A repository showcasing the problem: [link](https://github.com/robotjatek/FluentUiDialogFooterOverrideBug/tree/master)

On the home page there is a working example.

On the page `/crash` there is the same component but with `FluentDialogFooter` provided as a child.

## 🤔 Expected Behavior

The component should not crash.

## 😯 Current Behavior

The component throws an `InvalidOperationException` when providing a `FluentDialogFooter`

## 🔦 Context

I was trying to show a modal WITHOUT a dialog service.

## 🌍 Your Environment

* OS & Device: Windows
* Browser: Firefox
* .NET7

**Comment by konvolution** [comment]
FluentDialogFooter.Initialize is being called twice.

**Comment by dvoituron** [comment]
Thank you for your comments. This issue has been resolved in PR #920 and will be published in the next version.

**Comment by hksalessio** [comment]
I still get this error after updating to 3.4.0 :/ Has this only been fixed for 4.0.0?

**Comment by vnbaaij** [comment]
Yup, we forgot to include this in 3.4.0. Will be in the next (3.4.1) update.
